#page title
page_title                                : CHESSAGON                                       # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1229276250                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://kanesga.gitlab.io/chessagon.pages.io/  # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Like Chess . . . But With Triangles

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : SiliconLoom, LLC                               
your_link                                 : https://siliconloomllc.gitlab.io                    
your_city                                 : Minnesota                                
email_address                             : chessagon@gmail.com
facebook_username                         :                                           
instagram_username                        : the8Kengineer
twitter_username                          : the8Kengineer
github_username                           : the8Kengineer
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Custom Boards
    description                           : Choose from twelve different boards composed of natural Bamboo, Sandstone, Slate, Cork, Marble, Maple, Frost, Quiche, Furnace, Metal, Tropic and Picnic with space highlighting in complentary colors.
    fontawesome_icon_name                 : chess-board

  - title                                 : Custom Pieces
    description                           : Choose from twelve different styles of piece sets with four traditional styles like Keystone and Newline; or choose from eight new styles uniquely designed for play in triangular spaces like Alice, Iconic, Signet and Plumbline.
    fontawesome_icon_name                 : chess

  - title                                 : Pawn
    description                           : Moves forward one space to a space of the opposite color, point-to-point or face-to-face from its current position... Captures an opponent's piece by moving forward to a space of the same color, with points adjacent to its current space.
    fontawesome_icon_name                 : chess-pawn

  - title                                 : Bishop
    description                           : Moves on same color spaces along straight columns and rows in any of six directions, and must remain on its original color... Captures in the same way that it moves.
    fontawesome_icon_name                 : chess-bishop

  - title                                 : Rook
    description                           : Moves face-to-face along straight columns and rows in any of six directions, as long as it is not blocked by another piece... Captures in the same way that it moves.
    fontawesome_icon_name                 : chess-rook
  
  - title                                 : Duke
    description                           : Moves any number of spaces face-to-face then point-to-point in a straight line, in any of six directions, unless blocked by another piece... Captures in the same way that it moves.
    fontawesome_icon_name                 : shield-alt

  - title                                 : Queen
    description                           : Can move any number of spaces in any way that a Duke, a Rook, or a Bishop can move, as long as it is not blocked by another piece... Captures in the same manner as the Duke, the Rook, or the Bishop.
    fontawesome_icon_name                 : chess-queen

  - title                                 : Knight
    description                           : Jumps to one of twelve spaces of the opposite color, just beyond the triangle of spaces that surrounds it... Captures in the same way that it moves... Only piece that can position itself beyond the reach and threat of a Queen.
    fontawesome_icon_name                 : chess-knight

  - title                                 : King
    description                           : Can move one space in any of twelve directions... Moves one space face-to-face, one space point-to-point, or one space with points adjacent to it's current position... Capturing in the same way that it moves.
    fontawesome_icon_name                 : chess-king

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.2
topbar_title_color                        : "#ffffff"

cover_image                               : assets/DarkBlue1024.png                   # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  #  - vendor
  #  - .sass-cache/
  #   - .jekyll-cache/
  #  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown